const product = [

  {
    id: 1,
    name: "Classic Cotton Tee",
    price: "$20.23",
    image: '/men.jpg',
    description: "Premium breathable cotton fabric in excellent condition. Perfect for everyday casual wear.",
  },
  {
    id: 2,
    name: "Slim-Fit Oxford Shirt",
    price: "$20.23",
    image: '/men2.jpg',
    description: "A versatile essential for your wardrobe. High-quality fabric with a modern tailored fit.",
  },
  {
    id: 3,
    name: "Urban Crewneck Sweater",
    price: "$20.23",
    image: '/men4.jpg',
    description: "Soft-knit fabric designed for a relaxed feel and long-lasting durability.",
  },
  {
    id: 4,
    name: "Daily Essentials Shirt",
    price: "$20.23",
    image: '/men.jpg',
    description: "Lightweight and versatile, this piece is built for comfort and style in any setting.",
  },
  {
    id: 5,
    name: "Modern V-Neck Top",
    price: "$20.23",
    image: '/men10.jpg',
    description: "A sleek design crafted from high-grade textile for a sharp, clean, and professional look.",
  },
  {
    id: 6,
    name: "Relaxed Fit Polo",
    price: "$20.23",
    image: '/men12.jpg',
    description: "Breathable mesh fabric that keeps you cool while maintaining a polished appearance.",
  },
  {
    id: 7,
    name: "Button-Down Casual",
    price: "$20.23",
    image: '/men13.jpg',
    description: "Features a reinforced collar and premium stitching for a sophisticated, rugged finish.",
  },
  {
    id: 8,
    name: "Athletic Performance Tee",
    price: "$20.23",
    image: '/men14.jpg',
    description: "Moisture-wicking fabric designed for active lifestyles and maximum range of movement.",
  },
  {
    id: 9,
    name: "Vintage Style Flannel",
    price: "$20.23",
    image: '/men17.jpg',
    description: "Classic patterned fabric with a soft-brushed texture for extra warmth during cooler days.",
  },
  {
    id: 10,
    name: "Tailored Dress Shirt",
    price: "$20.23",
    image: '/men18.jpg',
    description: "Wrinkle-resistant material that stays crisp from morning meetings to evening dinner events.",
  },
  {
    id: 11,
    name: "Graphic Streetwear Tee",
    price: "$20.23",
    image: '/men20.jpg',
    description: "Heavyweight cotton with a bold aesthetic, perfect for modern urban street style.",
  },
  {
    id: 12,
    name: "Lightweight Linen Shirt",
    price: "$20.23",
    image: '/men21.jpg',
    description: "The ideal choice for warm weather, offering natural airflow and a relaxed, breezy vibe.",
  },
  // women product 
  {
    id: 13,
    name: "Floral Summer Dress",
    image: "/women1.jpg",
    price: "12.23",
    description: "Elegant floral print on a light, flowing fabric perfect for sunny garden parties.",
  },
  {
    id: 14,
    name: "Boho Chic Blouse",
    image: "/women2.jpg",
    price: "12.23",
    description: "Intricate detailing and a soft silhouette for a refined and artistic bohemian look.",
  },
  {
    id: 15,
    name: "High-Rise Skinny Jeans",
    image: "/women3.jpg",
    price: "$12.23",
    description: "Stretch-denim fabric that provides a flattering fit and comfortable all-day wear.",
  },
  {
    id: 16,
    name: "Classic Trench Coat",
    image: "/women5.jpg",
    price: "$12.23",
    description: "A timeless layering piece featuring a weather-resistant finish and adjustable waist belt.",
  },
  {
    id: 17,
    name: "Knitted Evening Cardigan",
    image: "/women6.jpg",
    price: "$12.23",
    description: "Delicate knit patterns with a subtle shimmering finish for sophisticated special occasions.",
  },
  {
    id: 18,
    name: "Pleated Midi Skirt",
    image: "/women8.jpg",
    price: "$12.23",
    description: "A sophisticated skirt with precise pleats that move beautifully with every step you take.",
  },
  {
    id: 18, // Keeping the duplicate ID as it was in your source
    image: "/women9.jpg",
    price: "$12.23",
    name: "Satin Wrap Top",
    description: "Lustrous satin fabric with a wrap-around design for an adjustable, high-fashion fit.",
  },
  {
    id: 19,
    image: "/women10.jpg",
    price: "$12.23",
    name: "Active Yoga Leggings",
    description: "High-compression, squat-proof fabric designed for support during the most intense workouts.",
  },
  {
    id: 20,
    image: "/women11.jpg",
    price: "$12.23",
    name: "Off-Shoulder Silk Gown",
    description: "A stunning formal piece crafted from premium silk-blend material with a draped neckline.",
  },
  {
    id: 21,
    image: "/women12.jpg",
    price: "$12.23",
    name: "Casual Denim Jacket",
    description: "Rugged yet stylish denim with a faded wash and copper buttons for a vintage aesthetic.",
  },
  {
    id: 22,
    image: '/phone1.jpg',
    name: "iPhone XR - Renewed",
    price: "$300.91",
    description: "Features a 6.1-inch Liquid Retina display and powerful A12 Bionic chip performance.",
  },
  {
    id: 23,
    image: "/phone2.jpg",
    name: "iPhone 13 - Midnight",
    price: "$230",
    description: "Dual-camera system and superfast 5G performance in a sleek, ceramic shield design.",
  },
  {
    id: 24,
    image: '/phone10.jpg',
    name: "Nokia Classic Edition",
    price: "$17.22",
    description: "Exceptional battery life and a rugged build for essential, distraction-free communication.",
  },
  {
    id: 25,
    image: '/phone11.jpg',
    name: "Google Pixel 8 Pro",
    price: "$4000.22",
    description: "The ultimate AI-powered smartphone experience with an incredible pro-level triple camera.",
  },
  {
    id: 26,
    image: '/phone12.jpg',
    name: "iPhone 16 Plus",
    price: "$1700.22",
    description: "The latest innovation featuring the Action button and advanced spatial video capture.",
  },
  {
    id: 27,
    image: '/phone18.jpg',
    name: "Samsung Galaxy A07",
    price: "$172.22",
    description: "Large immersive Infinity-V display and a long-lasting battery for consistent everyday use.",
  },
  {
    id: 28,
    image: '/phone19.jpg',
    name: "iPhone 17 Concept",
    price: "$1711.22",
    description: "Next-generation hardware with ultra-slim titanium housing and an under-display camera.",
  },
  {
    id: 29,
    image: '/charge1.jpg',
    name: "Fast Charging Block",
    price: "$6.22",
    description: "High-speed 20W power delivery adapter for quick and efficient charging at home.",
  },
  {
    id: 30,
    image: '/charge3.jpg',
    name: "USB-C Braided Cable",
    price: "$2",
    description: "Tangle-free reinforced nylon cable for high-speed data sync and rapid power transfer.",
  },
  {
    id: 31,
    image: '/charge20.jpg',
    name: "Tecno Power Adapter",
    price: "$4",
    description: "Compact wall charger optimized for global safety standards and consistent voltage.",
  },
  {
    id: 32,
    image: '/jew.jpg',
    name: "Silver Hand Bracelet",
    price: "$10.22",
    description: "Elegant sterling silver link chain featuring a high-polished lobster claw safety clasp.",
  },
  {
    id: 33,
    image: '/jew20.jpg',
    name: "24K Gold Plated Ring",
    price: "$20.22",
    description: "Luxurious gold-tone finish with a smooth, comfort-fit interior for daily elegance.",
  },
  {
    id: 34,
    image: '/jew8.jpg',
    name: "Gold Pendant Necklace",
    price: "$32.22",
    description: "A timeless gold chain featuring a minimalist geometric pendant for a modern look.",
  },
  {
    id: 35,
    image: '/toy.jpg',
    name: "Soft Plush Baby Doll",
    price: "$1.22",
    description: "Hypoallergenic, ultra-soft material that is safe, washable, and cuddly for infants.",
  },
  {
    id: 36,
    image: '/toy3.jpg',
    name: "Smart Walking Robot",
    price: "$4.22",
    description: "Interactive toy with LED lights and robotic sound effects to encourage creative play.",
  },
  {
    id: 37,
    image: '/toy4.jpg',
    name: "Glowing Toy Ring",
    price: "$5.2",
    description: "Fun, light-up accessory that is durable and perfect for children's party favors.",
  },
  {
    id: 38,
    image: '/sport1.jpg',
    name: "Pro Padding Ball",
    price: "$4.22",
    description: "Enhanced grip and shock absorption technology for competitive outdoor and indoor play.",
  },
  {
    id: 39,
    image: '/sport2.jpg',
    name: "Standard Soccer Ball",
    price: "$12.02",
    description: "Weather-resistant outer casing and precise machine stitching for a consistent flight path.",
  },
  {
    id: 40,
    image: '/sport4.jpg',
    name: "Inflatable Sports Ball",
    price: "$7.23",
    description: "High-rebound material suitable for a wide variety of indoor and outdoor gym activities.",
  },
  {
    id: 41,
    image: '/sport5.jpg',
    name: "Performance Field Stick",
    price: "$10.12",
    description: "Ergonomic design with a non-slip grip handle for maximum control and hitting power.",
  }
]

export default product;