# Generated by Django 5.2.8 on 2026-01-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_order_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, null=True)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('email', models.CharField(max_length=300, null=True)),
                ('street', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=400, null=True)),
                ('country', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
