# Generated by Django 5.2.8 on 2026-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('create_to', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
